services:
  web:
    build: .
    command: gunicorn oc_lettings_site.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=oc_lettings_site.settings.production
      - DJANGO_ENV=production
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    restart: always
