[tool.flake8]
max-line-length = 99
exclude = ["**/migrations/*", "venv"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "oc_lettings_site.settings"
python_files = ["tests.py", "test_*.py"]
python_classes = "Test*"
python_functions = "test_*"
addopts = ["-v"]